-- German Translation from AbrahamMoody: https://github.com/AbrahamMoody

local Translations = {
    error = {
        cantbuy = "Du kannst die Ölquelle nicht kaufen!",
        not_enough = "Du hast nicht genug",
        not_enough_cash = "Du hast nicht genug Geld!",
        alreadymax = "Du hast bereits die besten Upgrades!",
        alreadydone = "Das Upgrade ist bereits abgeschlossen!",
        nothing_to_sell = "Du hast nichts zu verkaufen!",
        cant_sell = "Du konntest nicht verkaufen!",
        not_owner = "Du bist nicht der Eigentümer der Ölquelle!",
        already_hired = "Dieser Bürger ist bereits angestellt!",
        none_around = "Es ist niemand um Dich herum!",
    },
    success = {
        repair = "Du hast die Ölquelle repariert!",
        remove_worker = "Du hast den Mitarbeiter entlassen!",
        bought_well = "Du hast die Ölquelle gekauft!",
        levelup = "Du bist jetzt Level: %d!",
        full_upgrade = "Du hast das Maximum aus dem Upgrade herausgeholt!",
        upgrade = "Du hast das Upgrade abgeschlossen!",
        sold_for = "Du verkaufst für: $%d!",
        collected_oil = "Du sammelst %d Öl!",
        put_out = "Du hast die Ölquelle für $%d!",
        changed_price = "Du hast den Preis geändert auf $%d!",
        hired = "Du hast den Bürger eingestellt!",
    },
    label = {
        watch = 'Überprüfen',
        oilwell = "Ölquelle",
        oil = "Öl",
        collect = "Abholen",
        collect_oil = "Pumpe %d Öl aus der Ölquelle ab",
        goback = "Zurückgehen",
        upgrade = "Upgrade",
        upgrading = "Aufwertung...",
        upgrade_well = "Ölquelle aufrüsten",
        repair = "Reparieren",
        repairing = 'Repariere Ölquelle..',
        fix = "Reparatur Ölquelle",
        sellwell = "Ölquelle verkaufen",
        putout = "Bestätigen",
        price = "Preis",
        sell = "Verkaufen",
        sell_well = "Ölquelle verkaufen",
        putout_sale = "Zum Verkauf anbieten",
        sell_to_others = "Öl an andere Bürger verkaufen",
        sell_quick = "Schnellverkauf",
        sell_for = "Verkaufe Ölquelle für $%d",
        info = "Information",
        info_well = "Informationen über die Ölquelle",
        level = "Level: ",
        oilwell_level = "Füllstand der Ölquelle",
        speed = "Geschwindigkeit: ",
        oilwell_speed = "Geschwindigkeit der Ölquelle",
        damage = "Schaden: ",
        per_second = "/s",
        oilwell_damage = "Schäden an Ölquellen",
        durability = "Zustand: ",
        oilwell_durability = "Zustand der Ölquelle",
        hire = "Mieten",
        no_match = "Keine Übereinstimmung",
        no_found = "Keinen Bürger gefunden.",
        administrate = "Mitarbeiter verwalten",
        hire_worker = "Mitarbeiter einstellen",
        hire_worker_1 = "Mitarbeiter hinzufügen",
        remove_worker = "Mitarbeiter entlassen",
        remove_worker_1 = "Mitarbeiter entlassen",
        buy_well = "Ölquelle kaufen",
        buy_well_1 = "Ölquelle kaufen für $%d!",
        buy_well_player = "Ölquelle eines anderen Bürger kaufen für $%d!",
        already_owned = "Es gehört schon jemandem!",
        no_access = "Du hast keinen Zugriff auf diese Ölquelle",
        exit = "Exit",
        sell_oil = "Öl verkaufen",
        collect = "Abpumpen",
        collect_rs = "Rohmaterial abpumpen",
        workers = "Mitarbeiter",
        worker_administrate = "Mitarbeiter verwalten",
    }
}

Lang = Locale:new({
    phrases = Translations,
    warnOnMissing = true
})
